"""
Alert Model
Stores anomaly detection alerts generated by ML models.
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Text, ForeignKey, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
from app.database import Base


class AlertStatus(str, enum.Enum):
    """Alert status enumeration."""
    NEW = "new"
    REVIEWED = "reviewed"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"
    TRUE_POSITIVE = "true_positive"


class AlertSeverity(str, enum.Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(Base):
    """Model for storing anomaly detection alerts."""
    
    __tablename__ = "alerts"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True)
    
    # Reference to traffic log
    traffic_log_id = Column(Integer, ForeignKey("traffic_logs.id"), nullable=False, index=True)
    
    # ML Detection results
    anomaly_score = Column(Float, nullable=False)  # 0.0 to 1.0
    risk_score = Column(Integer, nullable=False)  # 0 to 100 (Enhancement 2)
    severity = Column(SQLEnum(AlertSeverity), nullable=False, index=True)
    
    # Explanation and reasoning
    reasons = Column(JSON, nullable=False)  # List of explanation strings
    feature_contributions = Column(JSON, nullable=True)  # Feature importance data
    
    # ML Model information
    model_version = Column(String(50), nullable=True)  # Model version used
    model_type = Column(String(50), nullable=True)  # isolation_forest, autoencoder, etc.
    
    # Status and workflow
    status = Column(SQLEnum(AlertStatus), nullable=False, default=AlertStatus.NEW, index=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    traffic_log = relationship("TrafficLog", backref="alerts")
    feedback = relationship("Feedback", back_populates="alert", cascade="all, delete-orphan")
    recommendations = relationship("Recommendation", back_populates="alert", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Alert(id={self.id}, severity={self.severity}, score={self.anomaly_score}, status={self.status})>"

