"""Initial database schema

Revision ID: 1ea1fb1ec343
Revises: 
Create Date: 2025-12-26 14:58:13.745852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ea1fb1ec343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('context_key', sa.String(length=255), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_std', sa.Float(), nullable=True),
    sa.Column('metric_min', sa.Float(), nullable=True),
    sa.Column('metric_max', sa.Float(), nullable=True),
    sa.Column('metric_percentiles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_baseline_metric_context', 'baseline_stats', ['metric_name', 'context_type', 'context_key'], unique=False)
    op.create_index('idx_baseline_window', 'baseline_stats', ['window_start', 'window_end'], unique=False)
    op.create_index(op.f('ix_baseline_stats_context_key'), 'baseline_stats', ['context_key'], unique=False)
    op.create_index(op.f('ix_baseline_stats_created_at'), 'baseline_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_baseline_stats_id'), 'baseline_stats', ['id'], unique=False)
    op.create_index(op.f('ix_baseline_stats_metric_name'), 'baseline_stats', ['metric_name'], unique=False)
    op.create_index(op.f('ix_baseline_stats_window_end'), 'baseline_stats', ['window_end'], unique=False)
    op.create_index(op.f('ix_baseline_stats_window_start'), 'baseline_stats', ['window_start'], unique=False)
    op.create_table('traffic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('payload_size', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('query_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_traffic_created_at', 'traffic_logs', ['created_at'], unique=False)
    op.create_index('idx_traffic_timestamp_ip', 'traffic_logs', ['timestamp', 'src_ip'], unique=False)
    op.create_index('idx_traffic_url_status', 'traffic_logs', ['url', 'status_code'], unique=False)
    op.create_index(op.f('ix_traffic_logs_id'), 'traffic_logs', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_logs_method'), 'traffic_logs', ['method'], unique=False)
    op.create_index(op.f('ix_traffic_logs_src_ip'), 'traffic_logs', ['src_ip'], unique=False)
    op.create_index(op.f('ix_traffic_logs_status_code'), 'traffic_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_traffic_logs_timestamp'), 'traffic_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_traffic_logs_url'), 'traffic_logs', ['url'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traffic_log_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('reasons', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_contributions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'RESOLVED', 'FALSE_POSITIVE', 'TRUE_POSITIVE', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['traffic_log_id'], ['traffic_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_traffic_log_id'), 'alerts', ['traffic_log_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('FALSE_POSITIVE', 'TRUE_POSITIVE', 'INFORMATIVE', 'OTHER', name='feedbacktype'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('admin_user', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_alert_id'), 'feedback', ['alert_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_type'), 'feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('RATE_LIMIT', 'IP_BLOCK', 'PATTERN_MATCH', 'CHALLENGE', 'CUSTOM', name='ruletype'), nullable=False),
    sa.Column('rule_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_content', sa.Text(), nullable=True),
    sa.Column('rule_content_modsec', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('estimated_impact', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DEPLOYED', name='recommendationstatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_alert_id'), 'recommendations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_rule_type'), 'recommendations', ['rule_type'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('deployed_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_content', sa.Text(), nullable=False),
    sa.Column('rule_format', sa.String(length=50), nullable=False),
    sa.Column('rule_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REMOVED', name='rulestatus'), nullable=False),
    sa.Column('deployed_by', sa.String(length=100), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waf_rule_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployed_rule_status', 'deployed_rules', ['status', 'deployed_at'], unique=False)
    op.create_index(op.f('ix_deployed_rules_deployed_at'), 'deployed_rules', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_deployed_rules_id'), 'deployed_rules', ['id'], unique=False)
    op.create_index(op.f('ix_deployed_rules_recommendation_id'), 'deployed_rules', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_deployed_rules_rule_name'), 'deployed_rules', ['rule_name'], unique=False)
    op.create_index(op.f('ix_deployed_rules_rule_type'), 'deployed_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_deployed_rules_status'), 'deployed_rules', ['status'], unique=False)
    op.create_index(op.f('ix_deployed_rules_waf_rule_id'), 'deployed_rules', ['waf_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployed_rules_waf_rule_id'), table_name='deployed_rules')
    op.drop_index(op.f('ix_deployed_rules_status'), table_name='deployed_rules')
    op.drop_index(op.f('ix_deployed_rules_rule_type'), table_name='deployed_rules')
    op.drop_index(op.f('ix_deployed_rules_rule_name'), table_name='deployed_rules')
    op.drop_index(op.f('ix_deployed_rules_recommendation_id'), table_name='deployed_rules')
    op.drop_index(op.f('ix_deployed_rules_id'), table_name='deployed_rules')
    op.drop_index(op.f('ix_deployed_rules_deployed_at'), table_name='deployed_rules')
    op.drop_index('idx_deployed_rule_status', table_name='deployed_rules')
    op.drop_table('deployed_rules')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_rule_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_alert_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_type'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_alert_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_alerts_traffic_log_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_traffic_logs_url'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_timestamp'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_status_code'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_src_ip'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_method'), table_name='traffic_logs')
    op.drop_index(op.f('ix_traffic_logs_id'), table_name='traffic_logs')
    op.drop_index('idx_traffic_url_status', table_name='traffic_logs')
    op.drop_index('idx_traffic_timestamp_ip', table_name='traffic_logs')
    op.drop_index('idx_traffic_created_at', table_name='traffic_logs')
    op.drop_table('traffic_logs')
    op.drop_index(op.f('ix_baseline_stats_window_start'), table_name='baseline_stats')
    op.drop_index(op.f('ix_baseline_stats_window_end'), table_name='baseline_stats')
    op.drop_index(op.f('ix_baseline_stats_metric_name'), table_name='baseline_stats')
    op.drop_index(op.f('ix_baseline_stats_id'), table_name='baseline_stats')
    op.drop_index(op.f('ix_baseline_stats_created_at'), table_name='baseline_stats')
    op.drop_index(op.f('ix_baseline_stats_context_key'), table_name='baseline_stats')
    op.drop_index('idx_baseline_window', table_name='baseline_stats')
    op.drop_index('idx_baseline_metric_context', table_name='baseline_stats')
    op.drop_table('baseline_stats')
    # ### end Alembic commands ###
